# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'STRV Weather' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for STRV Weather
  
  # Rx
  pod 'RxSwift',    '~> 4.4.0'
  pod 'RxCocoa',    '~> 4.4.0'
  pod 'RxDataSources', '~> 3.0'
  
  # Location
  pod 'SwiftLocation', '~> 3.2.3', :inhibit_warnings => true # This Pod is showing a minor warning about  flatMap becoming deprecated
  
  
  target 'STRV WeatherTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
